### ISSUE TITLE
Deploy Environment

### ISSUE THREAD

**Issue by IvanMao714** [junhobaik/junhobaik.github.io#96]
Hello, there are some issue when I run your project maybe caused by environment
so, could you tell me your environment of the deploy?

**Comment by ocsxxi** [comment]
Hi, I'm a user of Junhobaik's awesome theme. I'd like to help you with this.

This is a project started in 2019, the dependencies are overdate, and the node requirement is 10 despite the newest stable node version is 18. The author hasn't committed to this repo since Dec of 2019 maybe because of hard work.

If you are still looking for the solution, follow these steps below:

1. Try to install the newest stable version of node. Mine is v18.16.0.

2. Clone my fork of this theme, you can find it on my repo page, the forked repo has been renamed as gatsby-theme-borderless. (original name to salute the original author). CLONE THE `borderlessX` BRANCH.
ps: the reason why I haven't made it a pull request is I wanna fix issues and make some promotions, the progress is still going on.

3. `yarn` or `npm install` to download the dependencies.

4. `yarn start` or `yarn build` to enjoy.

This is the solution that works on my computer. Welcome to email me for any problems with this theme.

**Comment by IvanMao714** [comment]
thanks for your help，if there is some problem i can‘t solve， i will email you🫡

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Zhiyuan Liu ***@***.***>
发送时间: Thursday, June 15, 2023 12:43:53 AM
收件人: junhobaik/junhobaik.github.io ***@***.***>
抄送: Ivan Mao ***@***.***>; Author ***@***.***>
主题: Re: [junhobaik/junhobaik.github.io] Deploy Environment (Issue #96)


Hi, I'm a user of Junhobaik's awesome theme. I'd like to help you with this.

This is a project started in 2019, the dependencies are overdate, and the node requirement is 10 despite the newest stable node version is 18. The author hasn't committed to this repo since Dec of 2019 maybe because of hard work.

If you are still looking for the solution, follow these steps below:

  1.  Try to install the newest stable version of node. Mine is v18.16.0.

  2.  Clone my fork of this theme, you can find it on my repo page, the forked repo has been renamed as gatsby-theme-borderless. (original name to salute the original author). CLONE THE borderlessX BRANCH.
ps: the reason why I haven't made it a pull request is I wanna fix issues and make some promotions, the progress is still going on.

  3.  yarn or npm install to download the dependencies.

  4.  yarn start or yarn build to enjoy.

This is the solution that works on my computer. Welcome to email me for any problems with this theme.
